/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/campaigns` | `/campaigns`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/tours` | `/tours`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/campaigns/[id]` | `/campaigns/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(client)'}/tours/[id]` | `/tours/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/campaigns` | `/campaigns`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/tours` | `/tours`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/campaigns/[id]` | `/campaigns/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(client)'}/tours/[id]` | `/tours/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(client)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/campaigns${`?${string}` | `#${string}` | ''}` | `/campaigns${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/tours${`?${string}` | `#${string}` | ''}` | `/tours${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/campaigns` | `/campaigns`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/tours` | `/tours`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(client)'}/campaigns/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/campaigns/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/tours/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tours/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(client)'}/campaigns/[id]` | `/campaigns/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(client)'}/tours/[id]` | `/tours/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
